### PR TITLE
Parser improvement

### PR DESCRIPTION
**Pull request by kulikalov**
A few parser improvements:

- [x] collapse empty sections when importing resume
- [x] allow brackets outside phone numbers
- [x] multi-line summary parsing
- [x] collapse empty sections only for returning users

### CODE REVIEW

**Comment by xitanggg** [comment]
Thanks so much @anton-k-git for creating this PR!! Amazing works and enhancements!

My only hesitation is "collapse empty sections when importing resume". Can you share more about this use case and why you think this is more desirable? 

My initial thinking is to default the core sections (experience, education, project, skill) to be expanded by default. (though project is not necessarily the core if folks have more work experiences.) My concern is that say someone doesn't list skills in their existing resume. It would be helpful to have skills expanded so they know it is better to fill out the section.

**Comment by anton-k-git** [comment]
Sure. I've loaded CV several times for editing and job-specific adjustments. I find it slightly annoying that I have to uncheck all of the unused sections every time. If I export a CV from open-resume and then upload it back, I would like to see it exactly the way it was last time I edited it in the open-resume.

**Comment by xitanggg** [comment]
Got it, thanks so much for your clarification! That is a good call and is indeed not a good UI/UX experience. 

2 ideas I can think of are
Idea 1. Load `settings` with `loadStateFromLocalStorage (src/app/lib/redux/local-storage.ts)`, and if it exists, simply preserve user's existing setting instead of using `initialSettings` as the default. Would this work for your use case?

or Idea 2. Keep what you have but add an if statement to override the setting for non first time user, where `isFirstTimeUser = !Boolean(loadStateFromLocalStorage())`, so first time user might still see the recommended section expanded. If idea 1 doesn't work, would idea 2 work?

Also, as a side note, it is interesting that you are loading resume several times for editing and job-specific adjustments. Given the state is preserved in local storage, is there a reason you would have to reupload instead of continue with the previous data? Thanks

**Comment by anton-k-git** [comment]
Why am I loading resume several times: because I need different versions for different cases. Also, it provides some form of version control.

Done, now the hide-empty-sections logic is applied only for returning users.
I implemented a new method `isLocalStorageEmpty` in the `local-storage.ts` to avoid executing the JSON parse operation. Seems to be a nice fit for this codebase convention.

**Comment by xitanggg** [comment]
Apologize for the delay in getting back. Had a hectic week with apartment hunting. 

Interesting use case. Thanks for sharing your use case and making the changes!

I just pushed an update with some small changes made:
- Rename `isLocalStorageEmpty` to `getHasUsedAppBefore` so the logic can be shared by `/resume-import` page. I also update its checked logic from looking at `localStorage.length` to `Boolean(loadStateFromLocalStorage())`. The reason is that I use `http://localhost:3000` quite often for development and its `localStorage` is almost never empty. Making the logic more precise to OpenResume by only looking at the `open-resume-state` key would make it easier to test things locally.
- Remove `lodash` dependency in favor of custom `deepClone` util and method. It seems the use case is simple and might be helpful to use the custom utils/methods without loading external dependency that adds some extra KBs. Also, the original `isEmpty` has a bug checking `skills` and `custom` since they are always an object. The added custom method check is more precise and fixes this issue.
- Add a `returnConcatenatedStringForTextsWithSameHighestScore` flag argument to `getTextWithHighestFeatureScore`, so the return concatenated string is an opt in only behavior, since it might cause some unintended bugs if it is default opt in for all use cases. Releasing it only to summary is a safer bet. Just a note that the current summary heuristics isn't great and the last line might not be detected if it has less than 4 words (See `SUMMARY_FEATURE_SETS`). We can enhance it but I will leave it for now.

Let me know what you think of the new changes and if it is ready to merge. Thanks!

**Comment by xitanggg** [comment]
Thanks for confirming! Just rebased and merged 🚀

**Comment by ranjibansal19** [comment]
i need this project with improvement.. please wtsapp me at 0091 8295842337..

**Comment by ranjibansal19** [comment]
or mail me at ranjibansal19@gmail.com

**Pull request merged**
