### PR TITLE
Add ability to add links to projects

### PR DESCRIPTION
**Pull request by p0lygun**
How it shows up 

image

image

> <picture>
>   <source media="(prefers-color-scheme: light)" srcset="https://raw.githubusercontent.com/Mqxx/GitHub-Markdown/main/blockquotes/badge/light-theme/tip.svg">
>   Tip
> </picture><br>
>
> We should extend this such that all "Headings" are link-able

### CODE REVIEW

**Comment by p0lygun** [comment]
How do i check what failed ?, also I've tried but failed to get the link out from projects in parser

**Comment by urbanogilson** [comment]
Great work on the PR!

What do you think about using the `[]()` Markdown style?
By using Markdown style or similar, we can extend the links to the description or to a specific word in the title.

**Comment by p0lygun** [comment]
I thought of that while implementing this, but decided against it as,
having link as a separate field is more accessible imo,

About markdown, i think we can have both the features as markdown is not
limited to just links

**Comment by Immortalin** [comment]
@p0lygun would you mind adding llink support for the Work Experience section too?

**Comment by p0lygun** [comment]
Hmm if I am going to do this, should I do it the `markdown` way? or keep it as a separate field, and add markdown support in the next PR

**Comment by Immortalin** [comment]
@p0lygun either works!

**Comment by p0lygun** [comment]
@xitanggg can you please review the PR, I am unable to extract URL in project section

**Comment by gargsms** [comment]
If we are adding links to projects, what about the description too? Markdown would help keep it simple.

**Comment by p0lygun** [comment]
I've added links as fields for now, IMO adding markdown support should be
down in a separate PR

**Comment by xitanggg** [comment]
Thanks so much @urbanogilson for your kind words/suggestions in #24 and also @p0lygun for creating this PR! Apologize for being super late at getting back. Things have been hectic on my end in the past few weeks. 

@p0lygun First of all, amazing work and great PR, especially given that you are a student. The code & technical side looks fine to me. However, I am not sure about this design and solution. My main concern is related to what you stated "I am unable to extract URL in project section". The problem with this solution is that it isn't ATS friendly since the link is embedded to the text and might not be visible to ATS just as it isn't visible to us readers. Also, if you print out the resume for a job fair, it would be odd that only the icon is visible. 

For anyone looking to get links to their projects, I personally would propose adding a description that spells out the link to your project (see example below). By default, the PDF renderer recognizes link and would make it clickable. This works best in all situations, whether it is digital or physical.

image

In regards to adding Markdown style, that would be a high effort, probably 3-5+ points, since you need to parse and render it, and you also need to think about what UI/UX makes sense. Agree that it is out of scope.

**Comment by igoose1** [comment]
@xitanggg, hey there and thanks for open-resume!

I came across this PR as I tried to add a Github link to a project. I like your approach but I struggle with this part:
> By default, the PDF renderer recognizes link and would make it clickable.

Was it said about a open-resume renderer or a HRs' PDF viewers? I've just tried to insert "Github: https://github.com/link-to/a-project" and it didn't work. A downloaded pdf-result was opened in a browser (Firefox) and a link can't be clicked.

If it's unexpected to you, maybe your own PDF viewer recognizes "https://..." links.

Should we file an issue to make links... well... links?

**Comment by p0lygun** [comment]
@igoose1 looks like firefox is not able to make links clickable, I believe that is out of the scope of this PR, please make a new Issue. 

@xitanggg .. Looking back at this, I agree with you that links in "icon" form no purpose. I think its better to have links as text if auto-detection of them works on all web browsers. I am closing this PR

**Pull request closed without merging**
